#!/usr/bin/env node
'use strict';

const write = require('fs').createWriteStream;
const bs = require('browser-sync').create();
const browserify = require('browserify');
const watchify = require('watchify');

bs.init({
	server: 'docs',
	files: ['./docs'],
	watchOptions: {
		ignoreInitial: true,
		ignored: 'docs/*.js'
	},
});

const b = browserify({
	entries: 'docs/app.js',
	plugin: [watchify],
	packageCache: {},
	cache: {}
});

function bundle() {
  b.bundle().pipe(write('docs/demo.js'));
}

b.on('update', bundle);
b.on('bundle', bs.reload);

bundle();
